/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jwintab */

#ifndef _Included_Jwintab
#define _Included_Jwintab
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jwintab
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Jwintab_close
  (JNIEnv *, jclass);

/*
 * Class:     Jwintab
 * Method:    getPacket
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Jwintab_getPacket
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     Jwintab
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Jwintab_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     Jwintab
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Jwintab_open
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
