/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jwintab_Jwintab */

#ifndef _Included_jwintab_Jwintab
#define _Included_jwintab_Jwintab
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jwintab_Jwintab
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jwintab_Jwintab_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     jwintab_Jwintab
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jwintab_Jwintab_open
  (JNIEnv *, jclass);

/*
 * Class:     jwintab_Jwintab
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jwintab_Jwintab_close
  (JNIEnv *, jclass);

/*
 * Class:     jwintab_Jwintab
 * Method:    getPacket
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_jwintab_Jwintab_getPacket
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
